### PR TITLE
Style new home page

### LINKED ISSUE #215: Make Home Page
- Just make a new page (It wont have a way to navigate to from the ui. For testing you can just use the url. `ex: http://localhost:3000/homepage`). Eventually we will want this to be our index.vue file, but that can be a next step. 
- I am assigning Ally to make a button component, so you can ignore the styling for this. Just get the guts of the page down. 
- Also, don't worry about the footer or the header. I will assign those in other issues. 

image

Designs here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5288&t=VlgvyNh92huHZLsA-1

### PR DESCRIPTION
**Pull request by judithweng**
Fixes #215 

This update is missing buttons but these will be added after button components are created.
image

### CODE REVIEW

**Comment by judithweng** [comment]
This is not set as the home page yet. You can go to this page by adding "/home" to the url.

**Comment by judithweng** [comment]
I noticed that the last section of the page is repeated in "How it works", "About us" and "Data and privacy" pages. Hence, I decided to make this section as a separate file "learn_more.vue" under layouts folder. This way we do not need to repeat the same code across the four pages.

image

**Review by RobertLRead — CHANGES_REQUESTED** [review]
The code looks fine, but I am having some trouble understanding it in toto. Can you please answer these questions before I approve?

1. The home page still has text that says " ** buttons go here **". This may be progress, but it seems unfinished. Maybe this screenshot below is needed:
Screenshot 2024-08-02 at 6 39 58 PM
2. The new home page looks good --- but there is NO link to it. I assume it should be linked from the icon which occurs at the top left of most pages. So you are making two nice pages, but I can't find a link to them.

**Comment by RobertLRead** [comment]
@judithweng can you answers these questions? I will re-review when you have answered this.

**Comment by judithweng** [comment]
@RobertLRead : 
1.  Issue #215 explains what I had to do and what I had to ignore. Katie meantions that the buttons are a separate issue assigned to Ally.
2. Issue #215 also mentions that at the moment there is no way to navigate to this page but that this will eventually become our home page, I assume once all the buttons are incorporated.

**Comment by RobertLRead** [comment]
Ohh okay my bad.

Robert L. Read, PhD
Twitter: @RobertLeeRead @pubinvention
Public Invention: https://www.pubinv.org
Join Our Mailing list: ***@***.***
YouTube: https://www.youtube.com/channel/UCJQg_dkDY3KTP1ybugYwReg
Medium: ***@***.***

**Review by RobertLRead — APPROVED** [review]
This looks good, I was hadn't read it closely enough.

**Pull request merged**
