### PR TITLE
Title bar is now a default layout (on all pages)

### LINKED ISSUE #100: new front end needs a title bar

### PR DESCRIPTION
**Pull request by K42IE**
fixes #100 

Other fixes:
- when you click the logo it now sends you to the default landing page (need about and contact pages)
- Fixed some design/formatting in the providence page. 

If you have questions about layouts please check out this video: https://www.youtube.com/watch?v=LZDQhOaBBbk

### CODE REVIEW

**Comment by K42IE** [comment]
I also made sure that there was the hamburger menu for mobile in this layout. I am making another issue to figure out how to fix the layout (will need to dynamically shrink the logo to fit (or both the logo and the h-menu)). 
image

**Comment by K42IE** [comment]
If you have questions about layouts please check out this video: https://www.youtube.com/watch?v=LZDQhOaBBbk

**Comment by devhawk** [comment]
Looks good in `npm run dev` but if I `npm run build` and `npm run preview` to test the preview build and navigate to the device page, I'm getting an error on the QR code generator and I get redirected to the home page.

Sample device: http://localhost:3000/device/3DZQDNpvt9dT8tNLYXENvt

Console spew: 
```
file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/_deviceKey_-DA8D7B8t.mjs:4
import QRCodeVue3 from 'qrcode-vue3';
       ^^^^^^^^^^
SyntaxError: The requested module 'qrcode-vue3' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async setup (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:845:76)
    at async Object.callAsync (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:89:16)
    at async applyPlugin (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:217:35)
    at async executePlugin (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:255:9)
    at async applyPlugins (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:263:5)
    at async createNuxtAppServer (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/chunks/build/server.mjs:1350:7)
    at async Object.renderToString (file:///home/harry/asset-provenance-tracking/packages/frontend/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
```

**Comment by devhawk** [comment]
the QR code error described in my last comment doesn't appear to be related to this PR. I am seeing the same behavior on the published site. I opened #178 to track

**Review by devhawk — APPROVED** [review]

**Pull request merged**
