### PR TITLE
changing favicon to GOSQAS favicon #94

### PR DESCRIPTION
**Pull request by RobertLRead**
This fixes bug #94 by simply using the GOSQAS favicon.

I did this mainly to prove that I could make the tiniest modification to Katie's new system.

### CODE REVIEW

**Comment by RobertLRead** [comment]
@devhawk this is trivial, please review and merge ASAP.

**Comment by devhawk** [comment]
Why are we updating `package-lock.json` in this PR?

**Comment by devhawk** [comment]
The icon looks good. Once we resolve the package-lock issue, I think this is ready to merge.

**Comment by RobertLRead** [comment]
@devhawk I've removed the changes to the package-lock.json. I'm pretty sure they occured by the natural upgrade of package values when you do an install. I don't know if there is a way to prevent that.

Because this is so simple and to avoid wasting time, I'm going to merge this without further review, having backed out the package-lock.json changes as you requested.

**Pull request merged**
