### PR TITLE
New title bar for front end and updated GUI

### PR DESCRIPTION
**Pull request by noramoor2007**
I made a sample About page and a contact page. I linked the sample devices to the old [https://gosqas.org](https://gosqas.org) sample devices because I am getting errors whenever I want to view the provenance record of a device that's made. Here is what it looks like right now:

Screen Shot 2024-05-20 at 3 45 53 PM
Screen Shot 2024-05-20 at 3 45 56 PM
Screen Shot 2024-05-20 at 3 46 00 PM
Screen Shot 2024-05-20 at 3 46 08 PM

### CODE REVIEW

**Comment by RobertLRead** [comment]
Change title to "Global Distributed Tracking"

**Comment by RobertLRead** [comment]
@noramoor2007 is the contact form suppose to work?  Did you actually tie it an email system? I would be surprised and impressed if you did this.

At present, I can't get this to work. I attempted to resolve the merge conflicts with main (in the future, you should probably do a merge of main into your branch and test it as the last step of the PR; it is never good to let branches get out of date.  After resolving some conflicts, I partially ran it; it looks attractive, and the About and Contact page work. However, it gives a number of warnings about missing components. (the log is included below.)  Possibly this is a build failure on my part; perhaps it works perfectly on your machine.

I need you to re-pull your branch, and examine the small commits that I have made (to fix the merge conflicts) and see if you approve them. Then please tell me if it is working for you and you can actually go to the history record for a newly created device (I cannot).

I could probably straighten this out without your help, but I am helping a friend move his domicile today, and will be doing manual labor all day.

```
[Vue warn]: Failed to resolve component: element
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: QRCodeVue3
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: element
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: textToLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by noramoor2007** [comment]
I am trying to make a pull request but it doesn't seem to be working. I still working at it, and about the contact form, it is not supposed to be working, I just included so we at least have it there, but I can get it working.

**Comment by RobertLRead** [comment]
Dear @noramoor2007 --- you may notice that there are conflicts in this branch (look up from here). These need to be resolved. I could of course resolve them, but it would be better for you to do so. This occurs when two people work on the same part of the code at the same time. Can you please attempt to resolve these conflicts?

**Comment by noramoor2007** [comment]
Yes I can do that.

**Comment by devhawk** [comment]
Is this PR still valid? I think there has been significant updates to the site style that may have made this PR outdated.

**Review by RobertLRead — COMMENTED** [review]
@noramoor2007 I am going to delete this pull request. I have taken the "contact" and "about" code that you wrote into a new branch. You did some valuable work (which is why I'm taking those pages), but the GUI and styling have progressed to the point of making this unmergable. The code I wrote is not really integratable either, but by approving (my own) pull request, the code will not have been a waste of time.

**Pull request closed without merging**
