### PR TITLE
Update main page to match style guide

### PR DESCRIPTION
**Pull request by judithweng**

### CODE REVIEW

**Comment by judithweng** [comment]
This PR contains the following changes:

1. Moves "CreateDevice.vue" and "CreateContainer.vue" to components/forms folder.
2. Fixing "Choose Files" buttons, changed text color to white and background color to purple.
3. Background on "Create New Device" and "Create New Container", changed from Sky color to Frost color
4. Input field filler text has been changed from gray color to black.
5. Remove border on input fields.
6. Added "Tags" input field
7. Added "Notify children?" checkbox. However it is still not in "Create Record"

Issues mentioned in #181  not addressed:
1. Correct toggle appearance: I believe Coco is working on this.
2. Correct font sizes, line heights, and spacing. Will create a separate issue for this.


@K42IE Would you be able to review this PR as well? Thank you!!

**Review by K42IE — APPROVED** [review]
Looks great! 👍🏻 :)

I pushed some small styling changes shown below (formatted the bottom labels and removed the ":" to fit the Figma): 
image

If you approve of these edits, I approve the push!

**Comment by judithweng** [comment]
@K42IE Tested and approved your changes! Thank you! @devhawk  If there are no conflicts on this branch once you merge #162 , would you be able to merge this as well? I will review this branch if there are any conflicts (there might be one small conflict).

**Comment by judithweng** [comment]
Recent push just addresses a simple change to fix the following warning: 

image

**Pull request merged**
