### PR TITLE
Adding attachment functionality

### PR DESCRIPTION
**Pull request by K42IE**
(builds upon past PR https://github.com/gosqasorg/asset-provenance-tracking/pull/62)

image

### CODE REVIEW

**Comment by K42IE** [comment]
Tested with multaple attachments: 
image

**Comment by K42IE** [comment]
Images/attachments are only displayed on their assigned record. 
image

**Comment by devhawk** [comment]
Note, I reset this PR branch back to https://github.com/gosqasorg/asset-provenance-tracking/pull/86/commits/2de9b76dcea022822a54d40f1d1c69e2e3fe382f. I saved @Htauqee 's work in [hira/favicon](https://github.com/gosqasorg/asset-provenance-tracking/tree/hira/favicon) branch

**Review by devhawk — APPROVED** [review]
Looks good. I think we're going to need a top level menu bar so user's can get back to the homepage easily, but we should do that as a separate PR

Note, we should close #62 in favor of this PR

**Pull request merged**
