### PR TITLE
Add Azure Function Backend Project

### LINKED ISSUE #55: Use cryptographically secure hash for device id

### LINKED ISSUE #56: Add Backend Logic

### PR DESCRIPTION
**Pull request by devhawk**
Adds the azure function backend that I've been working on in a different repo. 

I've written up some docs for how to invoke the endpoints: [Calling the GOSQAS backend](https://github.com/gosqasorg/asset-provenance-tracking/wiki/Calling-the-GOSQAS-backend)

fixes #56
fixes #55 (this PR uses SHA 256 instead of FNV for hashing)

### CODE REVIEW

**Review by RobertLRead — CHANGES_REQUESTED** [review]
I approve this code, but I am concerned that I will have lost the ability to run the code on my local machine, which was convenient with SQLLite. I suspect (I am not sure) that the README.md has not been updated with sufficient instructions for a user to know how to run this themselves.  Could that please be added? Or, if I am wrong, let me know. For example, can I create my own Azure account at a free level (different than the Public Invention one) and run it that way? I almost wish we had a middle lay (a "business-logic layer"), and the ability to swizel the persistence layer between Azure and other implementations. However, I think that is more than what we need for now.

**Comment by devhawk** [comment]
> I approve this code, but I am concerned that I will have lost the ability to run the code on my local machine

You can run this locally, but it requires a little more infrastructure. I will add a readme to the backend folder with the details

**Comment by devhawk** [comment]
`packages/backend/README.md` file added. @RobertLRead let me know if that provides enough information for you to run the backend locally

**Comment by RobertLRead** [comment]
I have read the README, thank you, it is very clear.  I will try it as soon as time allows, but I certainly approve it for now.

**Review by RobertLRead — APPROVED** [review]

**Pull request merged**
